spring:
  datasource:
    username: jiang
    password: kaoshixing1234
    url: jdbc:mysql://127.0.0.1:3306/jiangzhongchi?serverTimezone=Hongkong&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0ms
mybatis:
  type-aliases-package: kaoshixing_springboot.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#驼峰映射开启

companyMessage: companyMessage
